### ISSUE TITLE
Unexpected Behavior in PyQt6

### ISSUE THREAD

**Issue by Catphalem** [devhotteok/TwitchLink#178] opened 2023-10-31 00:01 UTC
Occasionally, PyQt6's C/C++ objects are forcibly deleted.
This issue primarily occurs with QTimer or QNetwork-related objects.

[TwitchLink_2023.10.30_09-00-48#cc9efbd6-a49b-4668-a66e-2118ec3a62ae.log](https://github.com/devhotteok/TwitchLink/files/13210670/TwitchLink_2023.10.30_09-00-48.cc9efbd6-a49b-4668-a66e-2118ec3a62ae.log)

**Comment by devhotteok** [comment] 2024-12-28 15:05
Hi there,
It has been quite a while since this issue was last discussed. During this time, numerous bug fixes have been implemented in Qt, and TwitchLink has also updated its base Qt version to the latest releases several times.
Given these updates, it is very likely that the issue caused by previous Qt bugs has been resolved. As a result, I am closing this issue.
However, if you encounter the same or a similar problem in the future, please feel free to open a new issue.

Closed with commit d5bf121291784c5643ade9c653ef822b5ea65b2b

**Closed by devhotteok** 2024-12-28 15:05 UTC
Labels: invalid
