### ISSUE TITLE
Compatibility with Kick.com streams?

### ISSUE THREAD

**Issue by TBloop** [devhotteok/TwitchLink#112] opened 2023-08-19 12:11 UTC
A great addition to the program would be the ability to also record streams on Kick. I understand this could potentially be difficult, but there are currently no other good programs that can record Kick streams. I've tried a few browser extensions which promise to record livestreams but they dont work properly.

**Comment by devhotteok** [comment] 2023-08-21 09:58
Duplicate of #103

**Closed by devhotteok** 2023-08-21 09:58 UTC
Labels: duplicate
