### ISSUE TITLE
RuntimeError due to QNetworkReply

### ISSUE THREAD

**Issue by newwave0225** [devhotteok/TwitchLink#126] opened 2023-08-21 14:48 UTC
[TwitchLink_2023.08.21_12-19-38#38b4ed54-4651-47d0-aed6-bd3ead61a952.log](https://github.com/devhotteok/TwitchLink/files/12397155/TwitchLink_2023.08.21_12-19-38.38b4ed54-4651-47d0-aed6-bd3ead61a952.log)
[TwitchLink_2023.08.21_12-27-05#62d7fd6a-1bb4-4f20-a314-52683dbe91d6.log](https://github.com/devhotteok/TwitchLink/files/12397157/TwitchLink_2023.08.21_12-27-05.62d7fd6a-1bb4-4f20-a314-52683dbe91d6.log)
[TwitchLink_2023.08.21_12-52-43#606b251f-72ff-4d6a-86de-d2dcfb39093f.log](https://github.com/devhotteok/TwitchLink/files/12397158/TwitchLink_2023.08.21_12-52-43.606b251f-72ff-4d6a-86de-d2dcfb39093f.log)
[TwitchLink_2023.08.21_13-17-01#f0392b54-a696-4b33-9a80-510a07f53ed6.log](https://github.com/devhotteok/TwitchLink/files/12397159/TwitchLink_2023.08.21_13-17-01.f0392b54-a696-4b33-9a80-510a07f53ed6.log)
[TwitchLink_2023.08.21_10-12-42#ce43ad86-15b6-41d4-ab4e-e0043bc28464.log](https://github.com/devhotteok/TwitchLink/files/12397160/TwitchLink_2023.08.21_10-12-42.ce43ad86-15b6-41d4-ab4e-e0043bc28464.log)
[TwitchLink_2023.08.21_10-12-54#17e16c21-1a77-4136-a7a9-f2a1fae67938.log](https://github.com/devhotteok/TwitchLink/files/12397161/TwitchLink_2023.08.21_10-12-54.17e16c21-1a77-4136-a7a9-f2a1fae67938.log)
[TwitchLink_2023.08.21_12-07-22#47e72831-df0a-4f69-bea5-61ec9aa154e9.log](https://github.com/devhotteok/TwitchLink/files/12397162/TwitchLink_2023.08.21_12-07-22.47e72831-df0a-4f69-bea5-61ec9aa154e9.log)

3.0.1 설치한지 약 두시간 반만에 오류 로그가 7개나 쌓여있습니다.

그리고 필수 업데이트 공지하는건 좋은데 이전 버전 프로그램 이용 중단하는건 개선해야한다 생각합니다.
컴퓨터에 프로그램 켜놓고 일 있어서 확인 못했는데 업데이트 공지 때문에 녹화 안돌아가는건 아니라고 봅니다.

**Comment by devhotteok** [comment] 2023-08-22 06:55
Duplicate of #124

**Closed by devhotteok** 2023-08-22 06:55 UTC
Labels: duplicate
