### ISSUE TITLE
TwitchLink.exe not exist

### ISSUE THREAD

**Issue by Mohmotte** [devhotteok/TwitchLink#144] opened 2023-08-26 22:29 UTC
I install the lastest release and in C:\Program Files\TwitchLink\TwitchLink.exe not exist

![Capture d’écran (267)](https://github.com/devhotteok/TwitchLink/assets/71752639/0e0712bb-174c-46b7-8d94-cfcecedc760a)

**Comment by devhotteok** [comment] 2023-08-27 07:37
Duplicate of #97

**Closed by devhotteok** 2023-08-27 07:37 UTC
Labels: duplicate

**Comment by Mohmotte** [comment] 2023-08-27 16:29
I uninstall a antivirus install by mistake and the lastest release work
