### ISSUE TITLE
can't access network drive issue (same #127)

### ISSUE THREAD

**Issue by kchwan1218** [devhotteok/TwitchLink#140] opened 2023-08-22 16:38 UTC
**normal working mode**
![image](https://github.com/devhotteok/TwitchLink/assets/38702357/732e0581-bffb-41c2-968f-184503100152)
![image](https://github.com/devhotteok/TwitchLink/assets/38702357/abfed63a-9e0c-4aba-8b61-e7b6afa99fc3)
![image](https://github.com/devhotteok/TwitchLink/assets/38702357/638323d1-8c1a-4123-99f1-205625fe936a)
[TwitchLink_Download_2023.08.22_16-32-43#e303ada8-eca4-4b67-aeb2-3d7ec5b39558.log](https://github.com/devhotteok/TwitchLink/files/12410778/TwitchLink_Download_2023.08.22_16-32-43.e303ada8-eca4-4b67-aeb2-3d7ec5b39558.log)

**administrator mode**

![image](https://github.com/devhotteok/TwitchLink/assets/38702357/c2503b6b-828f-4490-9844-8c293e500325)
![image](https://github.com/devhotteok/TwitchLink/assets/38702357/9f9ea2c7-057c-4a2d-894c-02bfbbbd5db0)

can't find network drive

**Comment by devhotteok** [comment] 2023-08-24 03:54
Duplicate of #127

**Closed by devhotteok** 2023-08-24 03:54 UTC
Labels: duplicate

**Comment by kchwan1218** [comment] 2023-08-25 15:47
> Duplicate of #127

solved in 3.1.0
thanks to upgrade
