### ISSUE TITLE
An error during the installation process

### ISSUE THREAD

**Issue by Hometownmp** [devhotteok/TwitchLink#152] opened 2023-09-08 15:06 UTC
Please provide a solution for this error.![스크린샷 2023-09-08 235652](https://github.com/devhotteok/TwitchLink/assets/144467339/6a33af64-6f02-4b9c-b555-1361ab0b30a3)

**Comment by devhotteok** [comment] 2023-09-24 07:25
Duplicate of #97

**Closed by devhotteok** 2023-09-24 07:25 UTC
Labels: duplicate
