### ISSUE TITLE
QWebEngine in PyQt causing unresponsiveness on some computers

### ISSUE THREAD

**Issue by iiJhas** [devhotteok/TwitchLink#146] opened 2023-08-30 20:58 UTC
Hi!!
Recently the program doesn't works when i open it:/
the screen turns white and closes.

**Comment by leirgab88** [comment] 2023-08-31 09:47
I have the same problem, hope it can be fixed soon. I really like this project and support it because it help me a lot

**Comment by iiJhas** [comment] 2023-09-03 16:18
> I have the same problem, hope it can be fixed soon. I really like this project and support it because it help me a lot

this project is the **only one** can download a complete stream without errors:/

**Comment by devhotteok** [comment] 2023-09-04 08:36
This problem has been reported for a long time.
I don't know the exact reason, but it appears to originate from the C++ part of PyQt.
The error appears to be related to compatibility issues with the Chromium WebEngine of PyQt.
Unfortunately, since it's related to a C++ issue with PyQt, there's nothing I can do about this now.

**Comment by devhotteok** [comment] 2023-09-04 08:44
This problem has been reported for a long time.
I don't know the exact reason, but it appears to originate from the C++ part of PyQt.
The error appears to be related to compatibility issues with the Chromium WebEngine of PyQt, which is being used to authenticate(login) the user.
Unfortunately, since it's related to a C++ issue with PyQt, there's nothing I can do about this now.

**Comment by devhotteok** [comment] 2024-12-28 15:05
Hi there,
It has been quite a while since this issue was last discussed. During this time, numerous bug fixes have been implemented in Qt, and TwitchLink has also updated its base Qt version to the latest releases several times.
Given these updates, it is very likely that the issue caused by previous Qt bugs has been resolved. As a result, I am closing this issue.
However, if you encounter the same or a similar problem in the future, please feel free to open a new issue.

Closed with commit d5bf121291784c5643ade9c653ef822b5ea65b2b

**Closed by devhotteok** 2024-12-28 15:05 UTC
Labels: invalid
