### ISSUE TITLE
Occasional Crash on Startup When Logged In

### ISSUE THREAD

**Issue by GodOfKnockers** [devhotteok/TwitchLink#221] opened 2024-10-05 03:22 UTC
If you are logged into your Twitch Account, and start the app for the first time the program reports that a network error has occurred and shuts down. When you open the app a second time, everything loads normally. 

This only happens when you load the program for the first time after booting up Windows.

**Comment by skyfox1977** [comment] 2024-10-06 12:32
> If you are logged into your Twitch Account, and start the app for the first time the program reports that a network error has occurred and shuts down. When you open the app a second time, everything loads normally.
> 
> This only happens when you load the program for the first time after booting up Windows.

This happens a lot of times for me on my laptop, but more rarely on my desktop computer, It would be much better if the app retries and retries and retries until it succeeds instead of shut down, sometimes I do not even see the network error message and the app is useless sitting there until I click the error message, and the app just exits without warning.  And no, there is nothing wrong with my network/internet, no other app behaves this way.

**Comment by devhotteok** [comment] 2024-10-29 07:38
I’ll take a closer look into this issue.

**Comment by devhotteok** [comment] 2024-12-28 15:06
Hi there,
It has been quite a while since this issue was last discussed. During this time, numerous bug fixes have been implemented in Qt, and TwitchLink has also updated its base Qt version to the latest releases several times.
Given these updates, it is very likely that the issue caused by previous Qt bugs has been resolved. As a result, I am closing this issue.
However, if you encounter the same or a similar problem in the future, please feel free to open a new issue.

Closed with commit d5bf121291784c5643ade9c653ef822b5ea65b2b

**Closed by devhotteok** 2024-12-28 15:06 UTC
Labels: invalid
