### ISSUE TITLE
Download Aborted [System Error] - Unable to save to network drives

### ISSUE THREAD

**Issue by MartynHolland-nl** [devhotteok/TwitchLink#139] opened 2023-08-22 15:29 UTC
Since updating to the 3.x's I have been unable to save anything to any network folders (as i normally do). tested on both Windows 11 and Windows Server 2019.

Tested saving to folders with correct permissions. Saving locally works fine. 

Both mapped drives and UNC do not work

relevant lines of log:

[2023-08-22 15:26:45,497][INFO] Download Failed
[2023-08-22 15:26:45,498][WARNING] Download failed for the following reason.
[2023-08-22 15:26:45,498][ERROR][BaseEngine.py:41] File System Error: Temporary Directory Error
This security ID may not be assigned as the owner of this object.

[TwitchLink_Download_2023.08.22_15-26-45#ae22ce29-0982-47a9-8b2b-1ea8068f1e2e.log](https://github.com/devhotteok/TwitchLink/files/12410276/TwitchLink_Download_2023.08.22_15-26-45.ae22ce29-0982-47a9-8b2b-1ea8068f1e2e.log)

**Comment by devhotteok** [comment] 2023-08-22 15:36
Duplicate of #127

**Comment by kchwan1218** [comment] 2023-08-22 15:36
i also can't download network drive

normal mode is can browse network drive but, can't save.
run as administrator mode is can't browse.

**Closed** 2023-08-22 15:36 UTC
Labels: duplicate
