### ISSUE TITLE
res problems when it's saved as 720p

### ISSUE THREAD

**Issue by Honinbo-Shusaku** [devhotteok/TwitchLink#71] opened 2023-03-03 21:19 UTC
first of all, thanks for your program

as you may know, Twitch Korea doesn't give us 1080p streaming anymore
and the problem is when we are going to get 720p instead, advertisements may intervene with it are still 1080p.
fortunately the video itself has no problems to see, but it is on the Premiere Pro, I can't save anything with it on that
I think all I have to do for this issue is just praying the ads would be same res as well or to subscribe.

I beg your understanding

**Comment by devhotteok** [comment] 2023-05-07 14:55
Duplicate of #50

**Closed by devhotteok** 2023-05-07 14:55 UTC
Labels: duplicate
