### ISSUE TITLE
Instability on downloads based on free space on disk

### ISSUE THREAD

**Issue by nameless01234567** [devhotteok/TwitchLink#174] opened 2023-10-22 05:58 UTC
I have a 1TB disk and whenever it fills to less 200GB of free space downloads start getting more unstable, depending on how much the I can't complete a download despite having enough free space for it. Also it starts causing errors on other programs that I'm using in the moment.
Maybe that's not the issue, but its my best guess with the log saying Error: None.
[TwitchLink_Download_2023.10.23_06-30-08#32ef6a5c-b3be-494f-8255-0917cbe44705.log](https://github.com/devhotteok/TwitchLink/files/13066878/TwitchLink_Download_2023.10.23_06-30-08.32ef6a5c-b3be-494f-8255-0917cbe44705.log)

**Comment by devhotteok** [comment] 2024-03-08 12:16
Duplicate of #173

**Closed by devhotteok** 2024-03-08 12:16 UTC
Labels: duplicate
