### ISSUE TITLE
TwitchLink has crashed due to an unexpected error.

### ISSUE THREAD

**Issue by skyfox1977** [devhotteok/TwitchLink#138] opened 2023-08-22 13:06 UTC
[TwitchLink_Download_2023.08.22_07-38-03#d9d436ba-676f-4afd-a2e8-072171c09e10.log](https://github.com/devhotteok/TwitchLink/files/12408880/TwitchLink_Download_2023.08.22_07-38-03.d9d436ba-676f-4afd-a2e8-072171c09e10.log)
[TwitchLink_2023.08.22_07-11-03#73316315-b9aa-4cac-ad0c-bf323e4fd431.log](https://github.com/devhotteok/TwitchLink/files/12408883/TwitchLink_2023.08.22_07-11-03.73316315-b9aa-4cac-ad0c-bf323e4fd431.log)

**Comment by devhotteok** [comment] 2023-08-22 15:16
Duplicate of #136

**Closed by devhotteok** 2023-08-22 15:16 UTC
Labels: duplicate
