### ISSUE TITLE
Scheduled downloading issues

### ISSUE THREAD

**Issue by gtskks** [devhotteok/TwitchLink#81] opened 2023-04-28 12:39 UTC
When using scheduled downloads, sometimes the recording time stops and the capacity keeps increasing.

When I check the .ts file, it is only recorded up to the time it stopped.

If I stop recording and turn it back on, it works fine.

It doesn't mean your network is down or something.

What could be the problem?

**Comment by devhotteok** [comment] 2023-05-07 14:42
Duplicate of #68

**Closed by devhotteok** 2023-05-07 14:42 UTC
Labels: duplicate
