### ISSUE TITLE
Downloading offline stream

### ISSUE THREAD

**Issue by slamdunk95** [devhotteok/TwitchLink#88] opened 2023-05-30 20:01 UTC
This issue just started recently and happens randomly. It may happen once a week, once every other day, or a few times a day. A scheduled stream will start downloading without issue, but when I check it after several hours the stream will be offline, but TwitchLink will still be downloading. After stopping the download, the file will be unplayable.

Version 2.3.2

**Comment by devhotteok** [comment] 2023-06-01 09:32
Duplicate of #68

**Closed by devhotteok** 2023-06-01 09:32 UTC
Labels: duplicate
