### ISSUE TITLE
option suggestion

### ISSUE THREAD

**Issue by infinityxgame** [devhotteok/TwitchLink#110] opened 2023-08-19 10:48 UTC
Hello, I have several suggestions that may be of help or that users like, I put them on the list:

1- Possibility of selecting a stream to download to copy the direct link of said stream.
2- If it were possible for the program to tell me the estimated weight of the stream to download, for example I select 720p quality and update the size and so on with the different qualities (I don't know if that is possible).
3- I like the design, it has what is necessary and it is beautiful, but a dark mode would be nice and that way it helps against vision problems.
4- Possibility of making multiple downloads as well as selecting the number of simultaneous downloads that the user wants in the application settings, for example, 2 or 3 streams can be downloaded at the same time.

I hope you read this and like the ideas, I'm not collaborating with the project since I don't know how to program but it would be a pleasure to help you, TwitchLink is super good, regards.

**Comment by infinityxgame** [comment] 2023-08-19 10:56
One last suggestion, sometimes when I go to download a stream and select a time range it happens to me that it shows me wrong when activating where to start, for example the boxes where the time goes get smaller and the numbers are not completely visible and other times the same thing happens to me but in the box where quality is selected, I put a photo so you can see where I say.

Now it doesn't happen to me because I customized my system with a theme simulating macOS but when I have the original windows bar it happens to me, this is because my screen is small with a 1366x768 resolution and I imagine that the lower the resolution other similar things happen. It is something silly that in higher resolutions it does not happen but thinking about the user, not everyone has the possibility of something greater.

![Ejemplo](https://github.com/devhotteok/TwitchLink/assets/38917076/d6d6dd74-4fc2-41d2-9418-ac5ca0fd8602)

**Comment by devhotteok** [comment] 2023-08-21 10:07
1. I don't understand what you mean.
2. Impossible
3. Duplicate of #40
4. Invalid due to internal changes in fb781c56d915871feb3561b2fc4f9a42046327af
5. I don't understand what you mean.

**Closed by devhotteok** 2023-08-21 10:07 UTC
Labels: invalid
