### ISSUE TITLE
Download errors

### ISSUE THREAD

**Issue by rrilink** [devhotteok/TwitchLink#84] opened 2023-05-06 05:14 UTC
Hello. I'm enjoying using TwitchLink. Thank you for creating the program.

It's happened several times recently where I set up a scheduled download, run it, and then it freezes a few hours later.
This happened yesterday. A streamer was broadcasting for 8 hours. The streamer broadcast for 5 hours and the recording was only 4 hours. I realized it wasn't working anymore, so I turned the program off and on again and ran the download again. It recorded for about an hour and then froze again. I turned it off and on again and ran the download again and it finished recording. I ended up with 3 files in one broadcast.

I have no idea why this happens so often. 

My suggestion is that it shouldn't happen, but I would like a notification window to pop up when it does.

**Comment by devhotteok** [comment] 2023-05-07 14:42
Duplicate of #68

**Closed by devhotteok** 2023-05-07 14:42 UTC
Labels: duplicate
