### ISSUE TITLE
Download History redownload doesn't work.

### ISSUE THREAD

**Issue by nameless01234567** [devhotteok/TwitchLink#205] opened 2024-07-02 23:18 UTC
If you go to Download History to try and download a VOD from there, it will give the "A network error has occured" most of the time, and then sometimes TwitchLink will force close.

Edit: Sometimes when opening a channel there will be the "A network error has occured", and then TwitchLink will force close.

**Comment by devhotteok** [comment] 2024-12-28 15:05
Hi there,
It has been quite a while since this issue was last discussed. During this time, numerous bug fixes have been implemented in Qt, and TwitchLink has also updated its base Qt version to the latest releases several times.
Given these updates, it is very likely that the issue caused by previous Qt bugs has been resolved. As a result, I am closing this issue.
However, if you encounter the same or a similar problem in the future, please feel free to open a new issue.

Closed with commit d5bf121291784c5643ade9c653ef822b5ea65b2b

**Closed by devhotteok** 2024-12-28 15:05 UTC
Labels: invalid
